### ISSUE TITLE
Optical-optical: pull down menu disappears after selecting a channel that is empty

### ISSUE THREAD

**Issue by bjboukens** [Quentin-Guille/rhythmTIS#172]
Please see following error:

Warning: 'popupmenu' control requires that 'Value' be an integer within String range
Control will not be rendered until all of its parameter values are valid 
Reference to non-existent field 'Analog1'.

Error in rhythmBasOpti_Opti2/scrn_popup_callback (line 2080)
                handles.analog1 = Data.Analog1(:,2:end);
 
Error while evaluating UIControl Callback

Warning: Error creating or updating Line
 Error in value of one or more of the following properties:  XData YData
 Array is wrong shape or size 
Warning: Error creating or updating Line
 Error in value of one or more of the following properties:  XData YData
 Array is wrong shape or size

**Comment by fernanben** [comment]
commit 6648b8f52b4b3197defeaff90f9e9b253d2d495c
