### ISSUE TITLE
Optical: function "regional APD map" does not work

### ISSUE THREAD

**Issue by bjboukens** [Quentin-Guille/rhythmTIS#180]
Warning: Error creating or updating Line
 Error in value of one or more of the following properties:  XData YData
 Array is wrong shape or size 
Warning: Error creating or updating Line
 Error in value of one or more of the following properties:  XData YData
 Array is wrong shape or size 
Index exceeds matrix dimensions.

Error in apdCalc (line 84)
        for k = maxValI(i,j):size(apd_data,3)

Error in rhythm1cam/createapd_button_callback (line 2389)
            apdCalc(handles.cmosData_1,apd_start,apd_end,handles.Fs,handles.percentAPD,handles.maxapd,...
 
Error while evaluating UIControl Callback

**Comment by Quentin-Guille** [comment]
Normally repaired with new released #182
