### ISSUE TITLE
heterogeneity function

### ISSUE THREAD

**Issue by fernanben** [Quentin-Guille/rhythmTIS#185]
give a vector with heterogeneity information

button heterogeneity on anal data 1 / anal data 2

check it with bas

commit a416547ed2b0c4f767a1b8f857b3f16585ea474a

**Comment by Quentin-Guille** [comment]
Normally repaired with new merge #186 
[release here](https://github.com/Quentin-Guille/rhythmTIS/releases/tag/v1.1-alpha-4)
