### ISSUE TITLE
APD/RT map

### ISSUE THREAD

**Issue by bjboukens** [Quentin-Guille/rhythmTIS#190]
I think this function also works well. 
Please adjust the following:

- While analyzing data i think it would be nice if to also have the option to choose the number of colors and isochrones.

- When I generate a regional APD/RT map I see the APDmap superimposed on the background picture. The color scale of this map is different from the APDmap next to it. Can you make the colors similar?

- The background picture seems flipped horizontally. Is it possible to fix this?

**Comment by fernanben** [comment]
commit f3d10efd58369ee5caaa4dac535e03be748e6781
