### ISSUE TITLE
export OAPs

### ISSUE THREAD

**Issue by celinepon** [Quentin-Guille/rhythmTIS#246]
si zoom avant export, les abscisses des signaux exportés sont fausses

**Comment by Quentin-Guille** [comment]
temporairement non reproductible

**Comment by Quentin-Guille** [comment]
quad on a un signal sur le panel de droie il y a une perte de zoom

**Comment by celinepon** [comment]
virer axe des abscises dans les screen au milieu des colonnes

**Comment by Quentin-Guille** [comment]
à tester

**Comment by celinepon** [comment]
bug reparé mais abscisses toujours visibles sur dual camera et single camera

**Comment by Quentin-Guille** [comment]
single cam done

**Comment by Quentin-Guille** [comment]
dual camera done

**Comment by Quentin-Guille** [comment]
volt_calcium done
