### ISSUE TITLE
export video interface voltage&calcium 

### ISSUE THREAD

**Issue by fernanben** [Quentin-Guille/rhythmTIS#252]
After a click on export video and validation of parameters.

Index exceeds matrix dimensions.

Error in aMap2 (line 9)
temp = data(:, :, start:endp); % windowed signal

Error in rhythmBasOpti_Calcium/expmov_button_callback (line 2332)
            actMap1 = aMap2(handles.cmosData, start_1, endp_1, handles.Fs);
 
Error while evaluating UIControl Callback.

**Comment by Quentin-Guille** [comment]
problème régler, la variable handles.cmosData été en fait handles.cmosData_1
