### ISSUE TITLE
Problem with removing background

### ISSUE THREAD

**Issue by bjboukens** [Quentin-Guille/rhythmTIS#297]
Undefined function or variable 'imbinarize'.

Error in remove_BKGRD (line 101)
BW = imbinarize(BG, level * thresh);

Error in rhythm_single_camera/cond_sig_selcbk (line 2004)
            current_data = remove_BKGRD(current_data, current_bg, bg_thresh, perc_ex);
 
Error while evaluating UIControl Callback

Undefined function or variable 'imbinarize'.

Error in remove_BKGRD (line 101)
BW = imbinarize(BG, level * thresh);

Error in rhythm_single_camera/cond_sig_selcbk (line 2004)
            current_data = remove_BKGRD(current_data, current_bg, bg_thresh, perc_ex);
 
Error while evaluating UIControl Callback

**Comment by Quentin-Guille** [comment]
same problem i's because you need matlab 2016 at least
