### ISSUE TITLE
Background problem in Voltage/calcium GUI

### ISSUE THREAD

**Issue by bjboukens** [Quentin-Guille/rhythmTIS#298]
Undefined function or variable 'imbinarize'.

Error in remove_BKGRD (line 101)
BW = imbinarize(BG, level * thresh);

Error in rhythm_voltage_calcium/cond_sig_selcbk (line 2886)
            current_data = remove_BKGRD(current_data, current_bg, bg_thresh, perc_ex);
 
Error while evaluating UIControl Callback

**Comment by Quentin-Guille** [comment]
the function was introduced in 2016 version of matlab so if your version is lower han 2016 it can't be used
