### ISSUE TITLE
Problem with generating RT/APDmap in dual camera GUI

### ISSUE THREAD

**Issue by bjboukens** [Quentin-Guille/rhythmTIS#301]
Error using rtCalc
Too many input arguments.

Error in rhythm_dual_camera/create_buttonR_callback (line 3073)
        gg = rtCalc(data, apd_start, apd_end, handles.Fs, handles.percentAPD,
        handles.maxapd, ...
 
Error while evaluating UIControl Callback

**Comment by celinepon** [comment]
corrected
