### ISSUE TITLE
ORCA doesnt work....

### ISSUE THREAD

**Issue by bjboukens** [Quentin-Guille/rhythmTIS#324]
Hey Quentin,

I am testing the rhythm software and generated an activation map. When I press the ORCA button then the first pop-up of ORCA appears (the one showing the killer whale). Then nothing happens. I also tried to directly open ORCA_Init.m and it is the same. Do you have an idea what can be wrong?

Best,

Bas

**Comment by Quentin-Guille** [comment]
![image](https://user-images.githubusercontent.com/19573868/28311126-f161581a-6bae-11e7-8744-51c29eea4dea.png)
you don't have this screen??

**Comment by Quentin-Guille** [comment]
![image](https://user-images.githubusercontent.com/19573868/28311179-1b237b88-6baf-11e7-940a-42cb12366d65.png)

**Comment by Quentin-Guille** [comment]
Even thought you open ORCA with Rhythm you have press OK to continue

**Comment by bjboukens** [comment]
Nope
<img width="966" alt="schermafbeelding 2017-07-18 om 11 59 37" src="https://user-images.githubusercontent.com/29378699/28311653-a240fa18-6bb0-11e7-94b3-59f1f5317d92.png">

**Comment by Quentin-Guille** [comment]
Do you have an error message?

**Comment by Quentin-Guille** [comment]
can you show me your current folder matlab like this :+1: 
![image](https://user-images.githubusercontent.com/19573868/28314485-06493534-6bbb-11e7-8d9b-84dc2e110868.png)

**Comment by Quentin-Guille** [comment]
this may help:
on line 37 of orca_init replace : 
pan = uipanel('Parent',f,'Unit','Pixel','Position',[358   55   200   250],'BackgroundColor',rgb_bg,'Borderwidth',3,'BorderType','beveledout','HighLightColor',rgb_bgl,'ShadowColor',rgb_bgld);

by

pan = uipanel('Parent',f,'Unit','Pixel','Position',[358 55 200 250],'BackgroundColor',rgb_bg,'Borderwidth',3);

**Comment by Quentin-Guille** [comment]
it's maybe due to difference between version of matlab

**Comment by bjboukens** [comment]
The line of code doesnt help. I use Matlab2016b. Lets look at it tomorrow.

Regards,

Bas
