### ISSUE TITLE
Bugs a reparer par quentin car c'est sa faute

### ISSUE THREAD

**Issue by celinepon** [Quentin-Guille/rhythmTIS#87]
enlever les axes sur les images
rajouter les axes sur les graphes de la fin
drag and drop
bouton bootstrap a enlever aussi

**Comment by celinepon** [comment]
bouton bootstrap a enlever aussi

**Comment by Quentin-Guille** [comment]
enlver les axes sur les inages done:
c85fed6b1aa739b56db249cdb8ad3a2c0b1a68fc #89

**Comment by Quentin-Guille** [comment]
rajouter les axes sur les graphes de la fin
c85fed6b1aa739b56db249cdb8ad3a2c0b1a68fc

**Comment by Quentin-Guille** [comment]
drag and drop et botstrap enlever:
6c803094943a88e6918254c69a03fe658df61e6c
👍
Correction
- mise à jour des points à display pour que le drag & drop fonctionne

👎
bug nouveau:
- tailles des images plus petites que la place donnée pour l'affichage
- comportement des points lors de la lecture

👎 bug potentiel / à teste:
- dépendance du code display button
- affichages des points à d'autre endroit du code

 ⚠️
disparition des images lorsque l'on clique en dehors --> à corriger
